name: Lacrei-eslint-config Publish
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  publish-lacrei-eslint-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@guilhermeabell'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}