name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        - name: Install dependencies
        run: npm install
        with:
          node-version: '18'
          registry-url: https://npm.pkg.github.com/
          scope: '@guilhermeabell'

      - name: Release
        run: npm run release
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}